"""check_refactor_v3

Revision ID: 23735bfa34f4
Revises: dcad5ab6544d
Create Date: 2026-02-14 16:19:37.276424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23735bfa34f4'
down_revision: Union[str, Sequence[str], None] = 'dcad5ab6544d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_results_assessment_type'), table_name='assessment_results')
    op.drop_index(op.f('ix_assessment_results_user_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_results',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('responses', sa.TEXT(), autoincrement=False, nullable=False, comment='JSON/text responses'),
    sa.Column('score', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('assessment_results_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_results_pkey'))
    )
    op.create_index(op.f('ix_assessment_results_user_id'), 'assessment_results', ['user_id'], unique=False)
    op.create_index(op.f('ix_assessment_results_assessment_type'), 'assessment_results', ['assessment_type'], unique=False)
    # ### end Alembic commands ###
