"""Add profile fields to User

Revision ID: fb01e5729ebe
Revises: 23735bfa34f4
Create Date: 2026-02-15 01:09:51.657082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb01e5729ebe'
down_revision: Union[str, Sequence[str], None] = '23735bfa34f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_results',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assessment_type', sa.String(), nullable=False),
    sa.Column('responses', sa.Text(), nullable=False, comment='JSON/text responses'),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_results_assessment_type'), 'assessment_results', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_assessment_results_user_id'), 'assessment_results', ['user_id'], unique=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True, comment='First name of the user'))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True, comment='Last name of the user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index(op.f('ix_assessment_results_user_id'), table_name='assessment_results')
    op.drop_index(op.f('ix_assessment_results_assessment_type'), table_name='assessment_results')
    op.drop_table('assessment_results')
    # ### end Alembic commands ###
